# twitter settings

consumer_key: TPAWsH0ww9uAnDD2ncvDs8n8e
consumer_secret: nJGB4iRyrSN7UEitvPnb08xfNqwjQ0JF5XEOsmJ8HZv82dhaKj
access_token: 108945861-5lDniEe0SAqrGvn9kdhWCKvq9aDwnUGcCygP9f0v
access_secret: 2njJaS9qyFvT55hbylBfaZwEipam1XJAoDLy7cnFzbSJW
